name: Build and Test Project

on:
  push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Create missing directories for testing
        run: |
          mkdir ConsoleApplicationTests\resources\LoadUpFolderContent_SingleLevelFolder
          mkdir ConsoleApplicationTests\resources\LoadUpFolderContent_SingleLevelFolder\level-1-folder
          mkdir ConsoleApplicationTests\resources\LoadUpFolderContent_ContainsOneFolderAndOneFile\level-1-folder\level-2-folder

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Run Tests
        run: dotnet test --logger "trx;LogFileName=test-results.trx" --results-directory TestResults
  
      - name: Upload Test Results
        if: always() # Ensure this step runs even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: TestResults
